title: Anh Tô-Lefebvre
logo: assets/img/avatar_round.png
description: Minimal is a theme for GitHub Pages.
linkedin: https://www.linkedin.com/in/anhlefebvre
github: https://github.com/anhlefebvre
email: contact@anhlefebvre.fr
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
plugins:
- jekyll-seo-tag
- jemoji
